[phases.setup]
nixPkgs = ["ffmpeg", "poppler_utils", "libreoffice"]
aptPkgs = ["ffmpeg", "poppler-utils", "libreoffice"]

[start]
cmd = "gunicorn -k uvicorn.workers.UvicornWorker -w ${WEB_CONCURRENCY:-2} -b 0.0.0.0:${PORT:-8000} main:app"
